name: plant_flutter
description: A place to buy plants from anywhere in the world.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  onesignal_flutter: ^3.3.0

  # Firebase
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  the_apple_sign_in: ^1.1.1
  flutter_staggered_grid_view: ^0.6.1

  nb_utils: ^4.4.14
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.0.20
  flutter_vector_icons: 1.0.0
  cached_network_image: ^3.2.0
  google_fonts: ^2.3.1
  flutter_staggered_animations: 1.0.0
  slide_to_act: ^2.0.1
  timeline_tile: ^2.0.0
  local_hero: ^0.2.0
  photo_view: ^0.13.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  geolocator: ^8.2.0
  flutter_speed_dial: ^5.0.0+1
  font_awesome_flutter: ^9.2.0
  tflite: ^1.1.2
  provider: ^6.0.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+4


  # Payment
  razorpay_flutter: ^1.2.9
  flutter_paystack:
                git:
                  url: https://github.com/definitelyme/flutter_paystack.git
                  ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

  html: ^0.15.0
  intl: ^0.17.0
  share_plus: ^4.0.4
  package_info_plus: ^1.4.0
  flutter_html: ^2.2.1

  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  webview_flutter: ^2.0.4

  # ADS
  google_mobile_ads: ^1.1.0

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  hive_generator:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/app/
    - asset/flag/
    - asset/icon/
    - asset/
    - asset/weather_icon/
    - asset/disease_images/
    - asset/fonts/
    - asset/model_tflite/model_unquant.tflite
    - asset/model_tflite/labels.txt
    - asset/model_tflite/

